// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package persistence

import (
	"database/sql"
)

type Task struct {
	ID             int32          `json:"id"`
	Type           sql.NullInt32  `json:"type"`
	Value          sql.NullInt32  `json:"value"`
	State          sql.NullString `json:"state"`
	CreationTime   sql.NullTime   `json:"creation_time"`
	LastUpdateTime sql.NullTime   `json:"last_update_time"`
}
