global:
  scrape_interval: 5ms  # Scrape every 5 milliseconds
  evaluation_interval: 10ms

scrape_configs:
  - job_name: 'producer'
    static_configs:
      - targets: ['producer:2112'] # Scrape producer's /metrics endpoint

  - job_name: 'consumer'
    static_configs:
      - targets: ['consumer:2113'] # Scrape consumer's /metrics endpoint