database:
  host: "db"
  port: 5432
  user: "admin"
  password: "password"
  dbname: "tasks_db"
  sslmode: "disable"

consumer:
  port: 2113
  profiling_port: 6061
  grpc_port: 50051

prometheus:
  scrape_interval: "15s"

logger:
  level: debug
  output_type: console

rate_limiter:
  tasks_per_second: 5